version: "3.9"
services:
  db:
    image: postgis/postgis:14-3.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: auro_user
      POSTGRES_PASSWORD: auro_pass
      POSTGRES_DB: auroshield
    ports:
      - "5432:5432"
    volumes:
      - ./database/migrations:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./infra/docker/backend.Dockerfile
    container_name: backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/auroshield
      SPRING_DATASOURCE_USERNAME: auro_user
      SPRING_DATASOURCE_PASSWORD: auro_pass
    ports:
      - "8080:8080"

  ai-service:
    build:
      context: .
      dockerfile: ./infra/docker/ai-service.Dockerfile
    container_name: ai-service
    ports:
      - "8000:8000"
    restart: always

volumes:
  db_data:
