version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: ./infra/docker/backend.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  ai-service:
    build:
      context: .
      dockerfile: ./infra/docker/ai-service.Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: ./infra/docker/frontend.Dockerfile
    ports:
      - "19006:19006"
    stdin_open: true
    tty: true


  db:
    image: postgis/postgis:14-3.3
    container_name: postgres
    environment:
      POSTGRES_USER: auro_user
      POSTGRES_PASSWORD: auro_pass
      POSTGRES_DB: auroshield
    ports:
      - "5432:5432"
    volumes:
      - ./database/migrations:/docker-entrypoint-initdb.d
