version: "3.9"
services:
  backend:
    build:
      context: ./infra/docker
      dockerfile: backend.Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  ai-service:
    build:
      context: ./infra/docker
      dockerfile: ai-service.Dockerfile
    container_name: ai-service
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./infra/docker
      dockerfile: frontend.Dockerfile
    container_name: frontend
    ports:
      - "19006:19006"  # Expo Dev server

  db:
    image: postgis/postgis:14-3.3
    container_name: postgres
    environment:
      POSTGRES_USER: auro_user
      POSTGRES_PASSWORD: auro_pass
      POSTGRES_DB: auroshield
    ports:
      - "5432:5432"
    volumes:
      - ./database/migrations:/docker-entrypoint-initdb.d
